# Autopiloot Configuration File
# Runtime settings for scraper, transcriber, summarizer, and assistant agents

# ID of the Google Sheet used for backfill links
sheet: "1AbC2defGhIJkLmNoPqRSTuVwxyz0123456789"

scraper:
  handles:
    - "@AlexHormozi"
  daily_limit_per_channel: 10

sheets:
  daily_limit_per_channel: 10
  range_a1: "Sheet1!A:D"

llm:
  default:
    model: "gpt-4.1"
    temperature: 0.2
    max_output_tokens: 1500
  prompts:
    summarizer_short_id: "coach_v1"
  tasks:
    summarizer_generate_short:
      model: "gpt-4.1"
      temperature: 0.2
      max_output_tokens: 1500
      prompt_id: "coach_v1"
      prompt_version: "v1"

notifications:
  slack:
    channel: "ops-autopiloot"

budgets:
  transcription_daily_usd: 5.0

idempotency:
  max_video_duration_sec: 4200  # 70 minutes maximum
  status_progression:
    - "discovered"
    - "transcribed" 
    - "summarized"
  drive_naming_format: "{video_id}_{date}_{type}.{ext}"

reliability:
  retry:
    max_attempts: 3  # Maximum retry attempts before DLQ
    base_delay_sec: 60  # Base delay for exponential backoff in seconds
  quotas:
    youtube_daily_limit: 10000  # YouTube Data API daily quota
    assemblyai_daily_limit: 100  # AssemblyAI daily transcription limit
