# Autopiloot Configuration File
# Runtime settings for orchestrator, scraper, transcriber, summarizer, observability, and linkedin agents

# Modular Agent Configuration
enabled_agents:
  - "orchestrator_agent"  # Required: CEO agent coordinates all workflows
  - "scraper_agent"       # YouTube content discovery
  - "transcriber_agent"   # Video transcription via AssemblyAI
  - "summarizer_agent"    # Business-focused summarization
  - "observability_agent" # Monitoring and notifications
  - "linkedin_agent"      # LinkedIn content ingestion
  - "strategy_agent"      # Strategic analysis and playbooks
  - "drive_agent"         # Google Drive content tracking

# Communication flows between agents (source -> target)
communication_flows:
  # CEO (orchestrator) coordinates all other agents
  - ["orchestrator_agent", "scraper_agent"]
  - ["orchestrator_agent", "transcriber_agent"]
  - ["orchestrator_agent", "summarizer_agent"]
  - ["orchestrator_agent", "linkedin_agent"]
  - ["orchestrator_agent", "strategy_agent"]
  - ["orchestrator_agent", "drive_agent"]
  - ["orchestrator_agent", "observability_agent"]

  # Primary content processing workflow
  - ["scraper_agent", "transcriber_agent"]      # Discovered videos -> transcription
  - ["transcriber_agent", "summarizer_agent"]   # Transcripts -> summaries

  # LinkedIn content analysis workflow
  - ["linkedin_agent", "strategy_agent"]        # LinkedIn content -> strategic analysis

  # Observability monitoring (bidirectional)
  - ["observability_agent", "scraper_agent"]
  - ["observability_agent", "transcriber_agent"]
  - ["observability_agent", "summarizer_agent"]
  - ["observability_agent", "linkedin_agent"]
  - ["observability_agent", "strategy_agent"]
  - ["observability_agent", "drive_agent"]

  # Error reporting and status updates back to observability
  - ["scraper_agent", "observability_agent"]
  - ["transcriber_agent", "observability_agent"]
  - ["summarizer_agent", "observability_agent"]
  - ["linkedin_agent", "observability_agent"]
  - ["strategy_agent", "observability_agent"]
  - ["drive_agent", "observability_agent"]

# ID of the Google Sheet used for backfill links
sheet: "1AbC2defGhIJkLmNoPqRSTuVwxyz0123456789"

scraper:
  handles:
    - "@AlexHormozi"
    - "@danmartell"
    - "@KimPerell"
  daily_limit_per_channel: 10
  page_size: 50  # Maximum number of videos to return per page (1-50)

sheets:
  daily_limit_per_channel: 10
  range_a1: "Sheet1!A:D"

llm:
  default:
    model: "gpt-4.1"
    temperature: 0.2
    max_output_tokens: 1500
  prompts:
    summarizer_short_id: "coach_v1"
  # Agent-specific model configurations
  agents:
    scraper_agent:
      model: "gpt-3.5-turbo"
      temperature: 0.3
      max_output_tokens: 4000
    transcriber_agent:
      model: "gpt-3.5-turbo"
      temperature: 0.1
      max_output_tokens: 4000
    summarizer_agent:
      model: "gpt-4.1"  # Keep GPT-4.1 for high-quality summarization
      temperature: 0.3
      max_output_tokens: 25000
    observability_agent:
      model: "gpt-3.5-turbo"
      temperature: 0.2
      max_output_tokens: 4000
    linkedin_agent:
      model: "gpt-3.5-turbo"
      temperature: 0.3
      max_output_tokens: 4000
    strategy_agent:
      model: "gpt-4.1"  # Keep GPT-4.1 for strategic analysis
      temperature: 0.4
      max_output_tokens: 25000
    drive_agent:
      model: "gpt-3.5-turbo"
      temperature: 0.2
      max_output_tokens: 4000
    orchestrator_agent:
      model: "gpt-4.1"  # Keep GPT-4.1 for complex orchestration
      temperature: 0.3
      max_output_tokens: 25000
  tasks:
    summarizer_generate_short:
      model: "gpt-4.1"
      temperature: 0.2
      max_output_tokens: 1500
      prompt_id: "coach_v1"
      prompt_version: "v1"

notifications:
  slack:
    channel: "ops-autopiloot"
    digest:
      enabled: true
      time: "07:00"
      timezone: "Europe/Amsterdam"
      channel: "ops-autopiloot"
      sections:
        - "summary"
        - "budgets"
        - "issues"
        - "links"

budgets:
  transcription_daily_usd: 5.0
  alert_threshold: 0.8  # 80% threshold for budget alerts

idempotency:
  max_video_duration_sec: 4200  # 70 minutes maximum
  status_progression:
    - "discovered"
    - "transcribed" 
    - "summarized"
  drive_naming_format: "{video_id}_{date}_{type}.{ext}"

reliability:
  retry:
    max_attempts: 3  # Maximum retry attempts before DLQ
    base_delay_sec: 60  # Base delay for exponential backoff in seconds
  quotas:
    youtube_daily_limit: 10000  # YouTube Data API daily quota
    assemblyai_daily_limit: 100  # AssemblyAI daily transcription limit

orchestrator:
  parallelism:
    max_parallel_jobs: 5  # Maximum concurrent jobs across all agents
    max_dispatch_batch: 10  # Maximum items per batch dispatch
  coordination:
    run_timeout_minutes: 120  # Maximum runtime for daily runs
    dlq_escalation_threshold: 5  # DLQ items before escalation
  policies:
    budget_enforcement: true  # Enable budget limit enforcement
    quota_enforcement: true  # Enable API quota enforcement
    max_retries_per_video: 3  # Global retry limit per video

linkedin:
  api:
    # RapidAPI host and key via environment variables:
    # RAPIDAPI_LINKEDIN_HOST and RAPIDAPI_LINKEDIN_KEY
    rate_limit_per_minute: 60  # Rate limiting for LinkedIn API calls
    max_posts_per_profile: 50  # Maximum posts to fetch per profile
  profiles:
    # Target LinkedIn profiles for content ingestion
    - "alexhormozi"  # Example LinkedIn username/handle
  zep:
    group_prefix: "linkedin"  # Prefix for Zep group names (e.g., "linkedin_posts", "linkedin_comments")
    collection_name: "linkedin_content"  # Zep collection for LinkedIn content
  processing:
    daily_limit_per_profile: 25  # Maximum content items per profile per day
    content_types:
      - "posts"
      - "comments"
      - "reactions"
    min_engagement_threshold: 5  # Minimum likes/comments to process content

drive:
  tracking:
    # Configured Drive files and folders to track for content changes
    targets:
      # Example folder configuration
      - type: "folder"
        id: "example_folder_id_here"
        recursive: true
        name: "Strategy Documents"
      # Example file configuration
      - type: "file"
        id: "example_file_id_here"
        name: "Playbook.docx"
    sync_interval_minutes: 60  # How often to check for changes
    max_file_size_mb: 10  # Maximum file size to process
    supported_formats:
      - ".txt"
      - ".md"
      - ".pdf"
      - ".docx"
      - ".html"
      - ".csv"

rag:
  zep:
    namespace:
      drive: "autopiloot_drive_content"  # Zep namespace for Drive content indexing

